name: Upload Packages

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Store dist for 2w
        uses: actions/upload-artifact@v2
        with:
          name: CrossPM packages
          path: dist/
          if-no-files-found: error
          retention-days: 14
