name: Build

on:
  workflow_call:
    inputs:
      py_version:
        description: 'Python version'
        default: '3.8'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.py_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel
          python -m pip install -r requirements.txt
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Store dist for 2w
        uses: actions/upload-artifact@v4
        with:
          name: CrossPM packages
          path: dist/
          if-no-files-found: error
          retention-days: 14
