name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build package
        run: python -m build
      - name: Store dist for 2w
        uses: actions/upload-artifact@v2
        with:
          name: CrossPM packages
          path: dist/
          if-no-files-found: error
          retention-days: 14
