name: Build and Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements-ci.txt
    - name: Run Tests
      run: |
        python -mflake8 crosspm
        python -mcoverage run -m py.test tests
    - name: Store dist for 2w
      uses: actions/upload-artifact@v2
      with:
        name: CrossPM packages
        path: dist/
        if-no-files-found: error
        retention-days: 14
