name: Tests

on:
  push:
    branches-ignore:
      - master
# Pull Requests can not reuse workflows from the source branch:
# https://github.com/actions/toolkit/issues/932
#  pull_request:
#    branches:
#      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements-ci.txt
      - name: Run Tests on Python ${{ matrix.python-version }}
        run: |
          python -mflake8 crosspm
          python -mcoverage run -m pytest tests
  build-artifact:
    uses: ./.github/workflows/build.yml
    needs: tests
